name: checks

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  jsonc:
    uses: ./.github/workflows/checks-jsonc.yml
  shell:
    uses: ./.github/workflows/checks-shell.yml
  yaml:
    uses: ./.github/workflows/checks-yaml.yml
